import { format } from "date-fns";
import { PurchaseItemSearchAdd } from "./purchaseModel";

export interface ImportPayload{
  file:File;
  mode:'merge' | 'replace' | 'rollback';
}
export interface PurchaseItem {
    purchaseitemId: string;
    itemName: string;
    purchasecategoryName: string;
    purchasesubcategoryName: any;
    itemgroupName: string;
    uom: string;
    stockQuantity: number;
    supplier: string;
    purchasePrice: number;
    randomId: string;
    purchasetaxName: string;
    reorderLevel: number;
    itemType: string;
    hsnCode: string;
    shelfLife: string;
    vendorTag: string[];
    locationName: string;
    barcode: string;
    description: string;
    status: string;
    createdDate: Date | null;
    lastUpdatedDate: Date | null;
  }
  
export interface ImportResponse {
  message: string;
  inserted_count?: number;
  updated_count?: number;
  backup_count?: number;
  mode: string;
  successful?: Array<{ row: number; data: Record<string, string> }>;
  updated?: Array<{ row: number; data: Record<string, string>; error?: string }>;
  failed?: Array<{ row: number; data: Record<string, string>; error: string; missingFields: string[] }>;
  errorCount?: number;
}

export interface PurchaseItemSearch {
    purchaseitemId: string;
    itemName: string;
  }
  
    // interface SearchState {
    //   purchaseItems: PurchaseItemSearch[];
    //   searchQuery: string;
    //   status: 'idle' | 'loading' | 'succeeded' | 'failed';
    //   error: string | null;
    // }
    // interface SearchParams {
    //   itemName?: string;
    //   skip?: number;
    //   limit?: number;
    // }
    
  export interface SearchResponse {
    total: number;
    items: PurchaseItemSearchAdd[];
  }

// Example function to format a date
export const formatDateTime = (date: Date): string => {
  // Format the date using date-fns format function
  return format(date, "dd:MM:yyyy hh:mm a"); // Example format string "dd:MM:yyyy hh:mm a"
};

// Usage example
const currentDate = new Date(); // Replace with your actual date
const formattedDate = formatDateTime(currentDate);
console.log(formattedDate); // Example output: "09:07:2024 03:30 PM"
// Define the Vendor interface

export interface UOM {
  uom: string;

}
export interface PurchaseTax {
  purchasetaxPercentage: string;
}

export interface StorageLocationItem {
  locationName: string;
}

export interface PurchaseGroupItem {
  itemgroupName: string;
}
export interface PurchaseItemType {
  itemtypeName: string;
}
export interface PurchaseCategory {
  purchasecategoryId: string; // Optional as it will be generated by the server
  purchasecategoryName: string;
  subcategories: string[]; // Assuming subcategories are sent as an array of strings (ids)
}

export interface Vendor {
  vendorId: string;
  vendorName: string;
}

export interface PurchaseItemState {
  items: PurchaseItem[];
  deactivatedItems: PurchaseItem[];
  loading: boolean;
  successMessage: string | null;
  error: string | null;
  searchQuery: string;
  categories: PurchaseCategory[];
  uoms: UOM[];
  taxes: PurchaseTax[];
  locations: StorageLocationItem[];
  groupitems: PurchaseGroupItem[];
  itemtypes: PurchaseItemType[];
  vendors: Vendor[];
  snackbarOpen: boolean;
  snackbarMessage: string;
  editIndex: number | null;
  dialogOpen: 'none' | 'edit' | 'deactivated';
  showDeactivated: boolean;
  itemData: PurchaseItem;
  itemToActivate: PurchaseItem | null;
  deactivateDialogOpen: boolean;
  activateDialogOpen: boolean;
  itemToDeactivate: PurchaseItem | null;
  tags: string[];
  currentPage: number; // New
  pageSize: number; // New
  totalItems: number; // New
  importStatus: 'idle' | 'loading' | 'succeeded' | 'failed';
  exportStatus: 'idle' | 'loading' | 'succeeded' | 'failed';
  exportError: string | null;
  filters: {
    itemName: string;
    purchasecategoryName: string;
    purchasesubcategoryName: string;
  };
  importError: string | null;
  importMessage: string | null,
  importResults: {
  successful: Array<{ row: number; data: Record<string, string> }>;
  updated: Array<{ row: number; data: Record<string, string>; error?: string }>;
  failed: Array<{ row: number; data: Record<string, string>; error: string; missingFields: string[] }>;
}
}

export const initialState: PurchaseItemState = {
  items: [],
  deactivatedItems: [],
  loading: false,
  successMessage: null,
  error: null,
  searchQuery: '',
  categories: [],
  uoms: [],
  taxes: [],
  locations: [],
  groupitems: [],
  itemtypes: [],
  vendors: [],
  snackbarOpen: false,
  snackbarMessage: '',
  editIndex: null,
  dialogOpen: 'none',
  showDeactivated: false,
  itemToActivate: null,
  deactivateDialogOpen: false,
  activateDialogOpen: false,
  itemToDeactivate: null,
  tags: [],
  currentPage: 1,
  pageSize: 50,
  totalItems: 0,
  itemData: {
    purchaseitemId: '',
    itemName: '',
    purchasecategoryName: '',
    purchasesubcategoryName: '',
    randomId: '',
    itemgroupName: '',
    uom: '',
    stockQuantity: 0,
    supplier: '',
    purchasePrice: 0,
    purchasetaxName: '',
    reorderLevel: 0,
    itemType: '',
    hsnCode: '',
    shelfLife: '',
    vendorTag: [],
    locationName: '',
    barcode: '',
    description: '',
    status: '',
    createdDate: null,
    lastUpdatedDate: null,
  },
  exportStatus: 'idle',
  exportError: null,
  filters: {
    itemName: '',
    purchasecategoryName: '',
    purchasesubcategoryName: ''
  },
  importError: null,
  importMessage: null,
  importStatus: 'idle',
  importResults: {
  successful: [],
  updated: [],
  failed: []
}
};
