name: Restrict Test  URL

on: [push, pull_request]

jobs:
  check_test_api_usage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Search for restricted test URL
        run: |
          echo "🔍 Checking for forbidden URL 'http://192.168.33.24:8000/purchaseapi'..."
          matches=$(grep -R -n \
            --exclude-dir=".git" \
            --exclude-dir="node_modules" \
            --exclude-dir=".github/workflows" \
            --exclude="check url.yml" \
            'http://192.168.33.24:8000/purchaseapi' . || true)

          if [ -n "$matches" ]; then
            echo "❌ Restricted test test URL found in the following places:"
            echo "$matches"
            exit 1
          else
            echo "✅ No restricted test URL found."
          fi


